cv_cosmos_site/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]


handler404='polls.views.costum_404'

polls/urls.py
from django.urls import path

from . import views

app_name ='polls'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('api/list', views.SerializedList.as_view(),),
    path('api/poll/<int:pk>', views.SerializedDetailView.as_view(),)
]

polls/models.py
from django.db import models
from django.core.serializers import serialize
import json


class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def total_votes(self):
        choices = Choice.objects.all().filter(question=self.pk).values('votes')
        total = 0
        for item in choices:
            total += item['votes']
        return total
    
    def get_choices(self):
        choices = Choice.objects.all().filter(question=self.pk)
        return choices


    def serialize(self):
        json_data = serialize('json', [self])
        deserialized = json.loads(json_data)
        obj = deserialized[0]
        obj['fields']['total_votes'] = self.total_votes()
        choies = self.get_choices()
        obj['fields']['choices'] = choies.serialize()
        final_json = json.dumps([{'data': obj['fields']}])
        return final_json

    def __str__(self):
        return self.question_text


class ChoiceQuerySet(models.QuerySet):
    def serialize(self):
        list_values = list(self.values('choice_text','votes'))
        return list_values
   

class ChoiceManager(models.Manager):
    def get_queryset(self):
        return ChoiceQuerySet(self.model, using=self._db)


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    objects = ChoiceManager()

    def __str__(self):
        return self.choice_text


    def serialize(self):
        json_data = serialize('json', [self], fields=('choice_text','votes'))
        return json_data

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse,Http404
from django.urls import reverse
from django.views import generic
import json

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        data = super(ResultsView,self).get_context_data(**kwargs)
        id_ = data['question'].id
        q = Question.objects.get(pk = id_)
        evaluated_chocies = []
        qs = q.get_choices()
        for item in qs:
            evaluated_chocies.append(item.votes)
        data['choices'] = evaluated_chocies
        return data


def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {'question' : question, 'error_message':"You didn't select a choice"})
    else: 
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))


class SerializedList(generic.DetailView):
    def get(self,request,*args,**kwargs):
        qs = Question.objects.all()
        data = serializers.serialize('json', qs,)

        return HttpResponse(data, content_type='application/json')


class SerializedDetailView(generic.DetailView):
      def get(self,request,*args,**kwargs):
        id_ = kwargs['pk']
        try:    
            q =  get_object_or_404(Question,pk=id_)
            context = q.serialize()
            return HttpResponse( context, content_type='application/json')
        except Question.DoesNotExist:
            return Http404('Something aint right')



def costum_404(request,exception):
    return render(request, 'polls/costum_404.html', {})            

polls/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <p class="h5 text-dark">Poll application</p>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'polls:index' %}">Poll List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'polls:index' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'polls:index' %}">Contact</a>
          </li>
   
        </ul>
      </div>
    </div>
  </nav>

polls/templates/polls/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Poll App</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- <link rel='stylesheet' type='text/css' href="{%static 'polls/style.css'%}"> -->
</head>

<body class="bg-dark text-white">

 

      {% include "navigation.html" %}

    <main  class="container  my-5">
        {% block content %}
        {% endblock %}
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

</body>

</html>

polls/templates/polls/costum_404.html
{%extends "polls/base.html" %}


{% block content %}

<main>
    <h2>Oh no something went wrong</h2>
    <a href="{% url 'polls:index' %}" class="btn btn-primary">Take me back to polls</a>
</main>


{% endblock %}

polls/templates/polls/details.html
{%extends "polls/base.html" %}

{% block content %}
<a class="btn-link my-3" href="{% url  'polls:index' %}">Back</a>
<div class="card text-dark my-3">
    <div class="card-header">
        <h1>{{ question.question_text }}</h1>
    </div>
    

    <div class="card-body">
        <form class="" action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <input type="radio" class="form-check-input" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label class="form-check-label mx-2" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <div class="d-grid col-sm-4">
                <input class="btn btn-primary my-2" type="submit" value="Vote">
            </div>
        </form> 
        {% if error_message %}<p class='text-danger font-bold'>{{ error_message }}</p>{% endif %}
    </div>

    <div class="card-footer">
        
    </div>
    
</div>

{% endblock %}

polls/templates/polls/index.html
{%extends "polls/base.html" %}


{% block content %}

<h1>Poll list</h1>
</button>

<ul class="list-group">
    {% for item in latest_list %}
    <li class="list-group-item"><a href="{{item.id}}">{{item}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

polls/templates/polls/results.html
{%extends "polls/base.html" %}


{% block content %}


<div class="card">
    <div class="card-header text-dark d-flex align-items-end">
        <h1>{{ question.question_text }}</h1>
        <p class="h4 mx-2">Total votes: {{question.total_votes}}</p>
    </div>

    <div class="card-body">
        <ul class="list-group border-0">
            {% for choice in question.choice_set.all %}
            <li class="list-group-item text-dark">
                {{ choice.choice_text }} -- <span class="percentageEl"></span>

                <div class="progress">
                    <div class="progress-bar" role="progressbar" id='{{forloop.counter0}}' style="width: 0%"
                        aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>


    <div class="card-footer">
        <a class="btn" href="{% url 'polls:details' question.id %}">Vote again?</a>
        <a class="btn" href="{% url 'polls:index' %}">Poll list</a>
    </div>
</div>

    {{ choices|json_script:'choices' }}
    {{ question.total_votes|json_script:'totalVotes' }}

{% load static %}
<script type="application/javascript" src="{% static '/js/voteProgress.js' %}"></script>
</body>

{% endblock %}